name: Dana&euml; Metaxa
title: Dana&euml; Metaxa
author: Dana&euml; Metaxa
url: https://dmetaxak.github.io
base: ''
twitter: '@dmetaxak'

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: rouge

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: about
      link: /index.html
    - title: research
      link: /research.html
    - title: CV
      link: /content/CV.pdf

theme: jekyll-theme-minimal

sass:
  sass_dir: _sass