name: Rayhan Rashed
title: Rayhan Rashed
author: Rayhan Rashed
url: https://rayhanrashe.me
base: ''
twitter: '@rayhanrashed'

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: rouge

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: about
      link: /index.html
    - title: research
      link: /research.html
    - title: CV
      link: /content/CV.pdf

theme: jekyll-theme-minimal

sass:
  sass_dir: _sass